#!/bin/bash
set -e

# Generates photo-wall/.env.local from the deployed CDK stack.
# Prerequisites: AWS CLI configured, stack already deployed.

STACK_NAME="TelegramPhotoWallStack"
REGION="${AWS_DEFAULT_REGION:-us-west-2}"
ENV_FILE="photo-wall/.env.local"

echo "Fetching resource IDs from stack: $STACK_NAME ($REGION)..."

TABLE_NAME=$(aws cloudformation describe-stack-resources \
  --stack-name "$STACK_NAME" --region "$REGION" \
  --query "StackResources[?ResourceType=='AWS::DynamoDB::Table'].PhysicalResourceId" \
  --output text)

BUCKET_NAME=$(aws cloudformation describe-stack-resources \
  --stack-name "$STACK_NAME" --region "$REGION" \
  --query "StackResources[?ResourceType=='AWS::S3::Bucket' && starts_with(LogicalResourceId,'Photo')].PhysicalResourceId" \
  --output text)

WEBHOOK_SECRET_ARN=$(aws secretsmanager describe-secret \
  --secret-id "telegram/webhook-secret" --region "$REGION" \
  --query "ARN" --output text)

# Read group config from cdk.json
GROUP_CONFIG=$(node -e "
  const cdk = require('./cdk.json');
  console.log(JSON.stringify(cdk.context.telegramGroups || []));
")

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup-local-env.sh — do not commit
# Re-run this script if stack resources change

AWS_REGION_NAME=$REGION
TABLE_NAME=$TABLE_NAME
BUCKET_NAME=$BUCKET_NAME
WEBHOOK_SECRET_ARN=$WEBHOOK_SECRET_ARN
GROUP_CONFIG=$GROUP_CONFIG
EOF

echo ""
echo "Written to $ENV_FILE:"
cat "$ENV_FILE"
echo ""
echo "Done. Run 'cd photo-wall && npm run dev' to start local dev server."
